language: csharp
solution: BioInformatics.Project3.sln
install:
  - nuget restore BioInformatics.Project3.sln
  - nuget install xunit.runner.console -Version 2.1.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release BioInformatics.Project3.sln
  - mono ./testrunner/xunit.runner.console.2.1.0/tools/xunit.console.exe ./tests/BioInformatics.Project3.Core.Tests/bin/Release/BioInformatics.Project3.Core.Tests.dll