language: csharp
solution: BioInformatics.Project3.sln
install:
  - nuget restore BioInformatics.Project3.sln
  - nuget install FAKE -version 4.45.1
  - nuget install xunit.runner.console -version 2.1.0
script:
  - mono /home/travis/build/MNie/BioInformatics.Project3/FAKE.4.45.1/tools/FAKE.exe build.fsx